### PR TITLE
Make default steempress easy to deploy on Heroku

### PR DESCRIPTION
**Pull request by bmann**
Hi -- I'm just getting started with Steemit and followed your work. I'm very interested in experimenting with distributed blogging systems.

I like using Heroku since I don't have to maintain a server at all. I made a variety of edits in this pull request which if you merge in, will let people launch their own version of Steempress on Heroku directly from the Github page.

### CODE REVIEW

**Comment by aaroncox** [comment]
That's great! Thanks so much and happy to have you involved and looks like a great pull request.

I have a few recommended changes for you though, in terms of project organization:
1. The composer.lock file should never be part of the github repository. Was there a specific reason you removed it from the ignore and then committed a version of it? The file is created when `composer install` runs on the environment. 
2. The `nginx_app.conf` should probably be loaded in `resources/config/heroku/nginx.conf`, and the `Procfile` itself should probably be `web: vendor/bin/heroku-php-nginx -C resources/config/heroku/nginx_app.conf web/`.

**Comment by bmann** [comment]
Heroku requires that you do check in composer.lock - https://devcenter.heroku.com/articles/php-support

Happy to make the changes in part 2, that makes sense.

**Comment by aaroncox** [comment]
Well that's interesting. Let me do some tests to make sure the docker container works OK with the composer.lock being included natively.

**Comment by bmann** [comment]
OK, I made those changes. Should be G2G whenever you check into composer.lock.

**Comment by aaroncox** [comment]
Awesome, yeah it's looking good. I haven't gotten a chance to test it out, hopefully within the next 24 hours.

**Comment by aaroncox** [comment]
Got this merged in, thanks so much! Looks like everything's working just fine with the composer.lock file being in source control. It caused no problems on my end, and after a few google searches, discovered how many people actually do this.

TBH I'm not exactly sure why I was convinced that was something you weren't supposed to check in... I've always ignored it. Learning something new every day 👍

**Pull request merged**
